### PR TITLE
Create LICENSE

### LINKED ISSUE #72: License
What is the license?

checklist

- [ ] merge #71
- [ ] add source code

### PR DESCRIPTION
**Pull request by Meow-purr**
cuold fix #72

### CODE REVIEW

**Comment by asjur** [comment]
I'd rather see another license like MIT or BSD than GPLv3

**Comment by Meow-purr** [comment]
see https://choosealicense.com/licenses/gpl-3.0/

**Comment by Meow-purr** [comment]
what about [AGPL](https://choosealicense.com/licenses/agpl-3.0/)

**Comment by Meow-purr** [comment]
> I'm rooting for [unlicense](https://unlicense.org/).
@cprivitere 

httpie/httpie iz [BSD 3-Clause "New"](https://github.com/httpie/httpie/blob/master/LICENSE) [or "Revised" License](https://choosealicense.com/licenses/bsd-3-clause/) and az such impossible

**Comment by cprivitere** [comment]
> > I'm rooting for [unlicense](https://unlicense.org/).
> > @cprivitere
> 
> httpie/httpie iz [BSD 3-Clause "New"](https://github.com/httpie/httpie/blob/master/LICENSE) [or "Revised" License](https://choosealicense.com/licenses/bsd-3-clause/) and az such impossible

Well shucks.

**Comment by Meow-purr** [comment]
it could be possible but only the gui is unlicensed(not httpie backend)

**Comment by jakubroztocil** [comment]
We only publish releases for now. Added a license file linking to HTTPie’s T&C: 

https://github.com/httpie/desktop/blob/master/LICENCE

**Pull request closed without merging**
